# Generated by Django 4.2.7 on 2023-11-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_url',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
